//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Authors = new HashSet<Author>();
            this.Genres = new HashSet<Genre>();
            this.Readers = new HashSet<Reader>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
        public string ISBN { get; set; }
        public int LanguageId { get; set; }
        public int PageNumber { get; set; }
        public System.DateTime PublishingDate { get; set; }
        public int PublisherId { get; set; }
        public int Weight { get; set; }
        public decimal Price { get; set; }
        public int FormatId { get; set; }
        public string Description { get; set; }
        public Nullable<int> SeriesId { get; set; }
        public int QuantityInStock { get; set; }
    
        public virtual Format Format { get; set; }
        public virtual Language Language { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Series Series { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<Reader> Readers { get; set; }
    }
}
