//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string SocialSecurityNumber { get; set; }
        public string Email { get; set; }
        public string CellPhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int AddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
