//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public int AddressId { get; set; }
        public int ContactId { get; set; }
        public string Comment { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderNumber { get; set; }
        public decimal TotalPrice { get; set; }
        public int DeliveryTypeId { get; set; }
        public int PaymentTypeId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual DeliveryType DeliveryType { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
